package com.pphi.tower.db;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class RelicSeeder {

    private final JdbcTemplate jdbc;

    public RelicSeeder(JdbcTemplate jdbc, DatabaseInitializer init) {
        this.jdbc = jdbc;
        seed();
    }

    private void seed() {
        Integer count = jdbc.queryForObject("SELECT COUNT(*) FROM relic", Integer.class);
        if (count != null && count > 0) return;
        seedRelics();
    }

    private void seedRelics() {
        relic("No Spoon", "Rare", "Standard", "Defense Absolute", 0.02, "Earn 350 medals Into the Matrix event", 0);
        relic("Red Pill", "Epic", "Standard", "Health", 0.05, "Earn 700 medals Into the Matrix event", 0);
        relic("Champion Badge", "Legendary", "Tournament", "Damage / Meter", 0.1, "Finish P4 in Champion", 0);
        relic("Copper Badge", "Rare", "Tournament", "Damage", 0.03, "Finish P4 in Copper", 1);
        relic("Gold Badge", "Epic", "Tournament", "Crit Factor", 0.05, "Finish P4 in Gold", 1);
        relic("Tower Master", "Legendary", "Tournament", "Health", 0.1, "Finish P4 in Legend", 0);
        relic("Silver Badge", "Rare", "Tournament", "Coins", 0.05, "Finish P4 in Silver", 1);
        relic("Platinum Badge", "Epic", "Tournament", "Lab Speed", 0.04, "Finish P4 in Platinum", 1);
        relic("T: XI Resonance", "Legendary", "Milestone", "Defense Absolute", 0.1, "Beat w4500 in T11", 1);
        relic("T:I Flux", "Rare", "Milestone", "Coins", 0.02, "Beat w4500 in T1", 1);
        relic("T: VI Nova", "Epic", "Milestone", "Defense Absolute", 0.05, "Beat w4500 in T6", 1);
        relic("T: XII Chrono", "Legendary", "Milestone", "Lab Speed", 0.1, "Beat w4500 in T12", 0);
        relic("T:II Lumin", "Rare", "Milestone", "Lab Speed", 0.015, "Beat w4500 in T2", 1);
        relic("T: VII Aether", "Epic", "Milestone", "Coins", 0.05, "Beat w4500 in T7", 1);
        relic("T: XIII Hyper", "Legendary", "Milestone", "Coins", 0.1, "Beat w4500 in T13", 0);
        relic("T:III Pulse", "Rare", "Milestone", "Crit Factor", 0.02, "Beat w4500 in T3", 1);
        relic("T: VIII Graviton", "Epic", "Milestone", "Damage / Meter", 0.05, "Beat w4500 in T8", 1);
        relic("T: XIV Arcane", "Legendary", "Milestone", "Damage", 0.1, "Beat w4500 in T14", 0);
        relic("T:IV Harmonic", "Rare", "Milestone", "Damage", 0.02, "Beat w4500 in T4", 1);
        relic("T: IX Fusion", "Epic", "Milestone", "Health", 0.05, "Beat w4500 in T9", 1);
        relic("T: XV Celestial", "Legendary", "Milestone", "Crit Factor", 0.1, "Beat w4500 in T15", 0);
        relic("T:V Ether", "Rare", "Milestone", "Health", 0.02, "Beat w4500 in T5", 1);
        relic("T: X Plasma", "Epic", "Milestone", "Damage / Meter", 0.05, "Beat w4500 in T10", 1);
        relic("T: XVI Quantum", "Legendary", "Milestone", "Health", 0.1, "Beat w4500 in T16", 0);
        relic("1st Tower Birthday", "Rare", "Anniversary", "Damage", 0.02, "Play for 1 year", 1);
        relic("Spirit Wolf", "Epic", "Standard", "Crit Factor", 0.05, "Earn 700 medals Full Moon event", 0);
        relic("T: XVII Nebula", "Legendary", "Milestone", "Damage / Meter", 0.1, "Beat w4500 in T17", 0);
        relic("2nd Tower Birthday", "Rare", "Anniversary", "Crit Factor", 0.02, "Play for 2 year", 0);
        relic("Neuron", "Epic", "Standard", "Health", 0.05, "Earn 700 medals Viral Outbreak event", 0);
        relic("T: XVIII Singularity", "Legendary", "Milestone", "Lab Speed", 0.1, "Beat w4500 in T18", 0);
        relic("3rd Tower Birthday", "Rare", "Anniversary", "Damage / Meter", 0.02, "Play for 3 year", 0);
        relic("Plasma Arc", "Epic", "Standard", "Lab Speed", 0.04, "Earn 700 medals Plasma Returns (II) event", 1);
        relic("T: XIX Atomic", "Legendary", "Milestone", "Damage", 0.1, "Beat w4500 in T19", 0);
        relic("4th Tower Birthday", "Rare", "Anniversary", "Health", 0.02, "Play for 4 year", 0);
        relic("Space Sundial", "Epic", "Standard", "Damage", 0.05, "Earn 700 medals Sands of Time event", 0);
        relic("T: XX Cyber", "Legendary", "Milestone", "Ultimate Damage", 0.08, "Beat w4500 in T20", 0);
        relic("5th Tower Birthday", "Rare", "Anniversary", "Crit Factor", 0.02, "Play for 5 year", 0);
        relic("Pumpkin", "Epic", "Standard", "Lab Speed", 0.04, "Earn 700 medals Autumn event", 0);
        relic("T: XXI Eclipse", "Legendary", "Milestone", "Lab Speed", 0.1, "Beat w4500 in T21", 0);
        relic("6th Tower Birthday", "Rare", "Anniversary", "Damage / Meter", 0.02, "Play for 6 year", 0);
        relic("Man Skull", "Epic", "Standard", "Health", 0.05, "Earn 700 medals Halloween event", 0);
        relic("Legend Badge", "Legendary", "Tournament", "Crit Factor", 0.1, "Win Legend", 0);
        relic("Dreamcatcher", "Rare", "Standard", "Coins", 0.02, "Earn 350 medals Full Moon event", 0);
        relic("Sakura Lantern", "Epic", "Standard", "Coins", 0.05, "Earn 700 medals Cherry Blossom (II) event", 1);
        relic("Bacteriophage", "Rare", "Standard", "Damage", 0.02, "Earn 350 medals Viral Outbreak event", 1);
        relic("Controller", "Epic", "Standard", "Crit Factor", 0.05, "Earn 700 medals Retro Arcade event", 0);
        relic("Ionized Plasma", "Rare", "Standard", "Defense Absolute", 0.02, "Earn 350 medals Plasma Returns (II) event", 1);
        relic("Stinger", "Epic", "Standard", "Crit Factor", 0.05, "Earn 700 medals Honey (II) event", 1);
        relic("Ancient Tome", "Rare", "Standard", "Lab Speed", 0.015, "Earn 350 medals Sands of Time event", 0);
        relic("Cheers", "Epic", "Standard", "Defense Absolute", 0.05, "Earn 700 medals New Year event", 0);
        relic("Tower Latte", "Rare", "Standard", "Damage / Meter", 0.02, "Earn 350 medals Autumn event", 0);
        relic("Contained Ions", "Epic", "Standard", "Defense Absolute", 0.05, "Earn 700 medals Aurora (II) event", 0);
        relic("Spooky Bat", "Rare", "Standard", "Crit Factor", 0.02, "Earn 350 medals Halloween event", 0);
        relic("Creepy Smile", "Epic", "Standard", "Damage", 0.05, "Earn 700 medals Dark Strands event", 0);
        relic("Cherry", "Rare", "Standard", "Defense Absolute", 0.02, "Earn 350 medals Cherry Blossom (II) event", 0);
        relic("Pixel Cube Heart", "Epic", "Standard", "Health", 0.05, "Earn 700 medals Retrowave (II) event", 1);
        relic("Holy Joystick", "Rare", "Standard", "Damage", 0.02, "Earn 350 medals Retro Arcade event", 1);
        relic("The Kraken", "Epic", "Standard", "Defense Absolute", 0.05, "Earn 700 medals Deep Blue Sea event", 0);
        relic("Honey Drop", "Rare", "Standard", "Damage", 0.02, "Earn 350 medals Honey (II) event", 1);
        relic("Alien Warp Drive", "Epic", "Standard", "Damage / Meter", 0.05, "Earn 700 medals Aliens (II) event", 1);
        relic("Firework", "Rare", "Standard", "Health", 0.02, "Earn 350 medals New Year event", 0);
        relic("Star Ship", "Epic", "Standard", "Lab Speed", 0.04, "Earn 700 medals Faster Than Light event", 0);
        relic("Aurora Vortex", "Rare", "Standard", "Health", 0.02, "Earn 350 medals Aurora (II) event", 1);
        relic("Wave", "Epic", "Standard", "Crit Factor", 0.05, "Earn 700 medals Ocean Night (II) event", 1);
        relic("Dark Sight", "Rare", "Standard", "Damage / Meter", 0.02, "Earn 350 medals Dark Strands event", 0);
        relic("Illuminati", "Epic", "Standard", "Defense Absolute", 0.05, "Earn 700 medals Invaders event", 1);
        relic("Palm Tree", "Rare", "Standard", "Lab Speed", 0.02, "Earn 350 medals Retrowave event (II)", 1);
        relic("Prismatic Shard", "Epic", "Standard", "Damage / Meter", 0.05, "Earn 700 medals Prismatic Lines (II) event", 0);
        relic("Submarine", "Rare", "Standard", "Crit Factor", 0.02, "Earn 350 medals Deep Blue Sea event", 0);
        relic("Fish", "Epic", "Standard", "Defense Absolute", 0.05, "Earn 700 medals Sunset Fishing event", 1);
        relic("Alien Head", "Rare", "Standard", "Coins", 0.02, "Earn 350 medals Aliens (II) event", 1);
        relic("The Fly", "Epic", "Standard", "Defense Absolute", 0.05, "Earn 700 medals Cobweb (II) event", 1);
        relic("Warp Gate", "Rare", "Standard", "Coins", 0.02, "Earn 350 medals Faster Than Light event", 0);
        relic("Flying House", "Epic", "Standard", "Damage", 0.05, "Earn 700 medals Into the Storm event", 1);
        relic("Barnacle", "Rare", "Standard", "Health", 0.02, "Earn 350 medals Ocean Night (II) event", 1);
        relic("Code Stream", "Epic", "Standard", "Damage", 0.05, "Earn 700 medals Into the Matrix (II) event", 1);
        relic("Pizza", "Rare", "Standard", "Damage", 0.02, "Earn 350 medals Invaders event", 1);
        relic("Cloud Lightning", "Epic", "Standard", "Crit Factor", 0.05, "Earn 700 medals Rainfall event", 0);
        relic("Refraction Array", "Rare", "Standard", "Coins", 0.02, "Earn 350 medals Prismatic Lines (II) event", 0);
        relic("Ebola", "Epic", "Standard", "Defense Absolute", 0.05, "Earn 700 medals Viral Outbreak (II) event", 1);
        relic("Hook", "Rare", "Standard", "Damage / Meter", 0.02, "Earn 350 medals Sunset Fishing event", 1);
        relic("Planetary Rings", "Epic", "Standard", "Crit Factor", 0.05, "Earn 700 medals Interstellar (III) event", 1);
        relic("Cobweb", "Rare", "Standard", "Health", 0.02, "Earn 350 medals Cobweb (II) event", 1);
        relic("Cathode Ray Tube", "Epic", "Standard", "Coins", 0.05, "Earn 700 medals Tower's Channel event", 1);
        relic("Gale Winds", "Rare", "Standard", "Coins", 0.02, "Earn 350 medals Into the Storm event", 1);
        relic("Sphinx", "Epic", "Standard", "Damage", 0.05, "Earn 700 medals Sands of Time (II) event", 0);
        relic("Clip Ons", "Rare", "Standard", "Crit Factor", 0.02, "Earn 350 medals Into the Matrix (II) event", 1);
        relic("Ash Cloud", "Epic", "Standard", "Defense Absolute", 0.05, "Earn 700 medals Volcano (III) Event", 0);
        relic("Rain Jacket", "Rare", "Standard", "Health", 0.02, "Earn 350 medals Rainfall event", 0);
        relic("Crop Circle", "Epic", "Standard", "Crit Factor", 0.05, "Earn 700 medals Abduction Event", 0);
        relic("Rabies", "Rare", "Standard", "Lab Speed", 0.02, "Earn 350 medals Viral Outbreak (II) event", 1);
        relic("Scarf", "Epic", "Standard", "Defense Absolute", 0.05, "Earn 700 medals Autumn (II) event", 1);
        relic("Comet", "Rare", "Standard", "Damage", 0.02, "Earn 350 medals Interstellar (III) event", 1);
        relic("Witch Hat", "Epic", "Standard", "Damage", 0.05, "Earn 700 medals Halloween (II) event", 0);
        relic("Remote Control", "Rare", "Standard", "Damage / Meter", 0.02, "Earn 350 medals Tower's Channel event", 1);
        relic("Sleigh Bell", "Epic", "Standard", "Health", 0.05, "Earn 700 medals Snowstorm event", 1);
        relic("Anubis", "Rare", "Standard", "Coins", 0.02, "Earn 350 medals Sands of Time (II) event", 0);
        relic("Bonsai Tree", "Epic", "Standard", "Coins", 0.05, "Earn 700 medals Cherry Blossom (III) event", 1);
        relic("Lava Flow", "Rare", "Standard", "Health", 0.02, "Earn 350 medals Volcano (III) Event", 0);
        relic("Kimono", "Epic", "Standard", "Coins", 0.05, "Earn 500 medals Cherry Blossom (III) event", 0);
        relic("Abduction Room", "Rare", "Standard", "Health", 0.02, "Earn 350 medals Abduction Event", 0);
        relic("Pet Cat", "Epic", "Standard", "Attack Speed", 0.02, "Earn 700 medals Meowy Night event", 0);
        relic("Acorn", "Rare", "Standard", "Damage / Meter", 0.02, "Earn 350 medals Autumn (II) event", 1);
        relic("Party Mask", "Epic", "Standard", "Ultimate Damage", 0.05, "Earn 700 medals New Year (II) event", 1);
        relic("Cauldron", "Rare", "Standard", "Lab Speed", 0.02, "Earn 350 medals Halloween (II) event", 0);
        relic("Mountain Goat", "Epic", "Standard", "Health", 0.05, "Earn 700 medals Full Moon (II) event", 0);
        relic("Icicle", "Rare", "Standard", "Damage", 0.02, "Earn 350 medals Snowstorm Event", 1);
        relic("3 Body Solution", "Epic", "Standard", "Super Critical Chance", 0.02, "Earn 700 medals Gravity event", 0);
        relic("Koi Fish", "Rare", "Standard", "Lab Speed", 0.02, "Earn 350 medals Cherry Blossom (III) event", 1);
        relic("Arcade Token", "Epic", "Standard", "Bot Range", 2.0, "Earn 700 medals Retro Arcade (II) event", 1);
        relic("Tea Ceremony", "Rare", "Standard", "Health", 0.02, "Earn 200 medals Cherry Blossom (III) event", 0);
        relic("Angler Fish", "Epic", "Standard", "Thorns", 0.02, "Earn 700 medals Deep Blue Sea (II) event", 1);
        relic("Lunar Cat Paw", "Rare", "Standard", "Crit Chance", 0.01, "Earn 350 medals Meowy Night event", 0);
        relic("Dream Clock", "Epic", "Standard", "Orb Speed", 0.05, "Earn 700 medals What Time Is It? event", 1);
        relic("Confetti Ball", "Rare", "Standard", "Free Attack Upgrade", 0.01, "Earn 350 medals New Year (II) event", 1);
        relic("Time Compass", "Epic", "Premium", "Attack Speed", 0.02, "Premium 1100 medals What Time Is It? event", 1);
        relic("Summit Starlight", "Rare", "Standard", "Lab Speed", 0.02, "Earn 350 medals Full Moon (II) event", 0);
        relic("Crown", "Epic", "Guild", "Crit Factor", 0.05, "Spend 150 Tokens in Guild Season 1", 0);
        relic("Falling Apple", "Rare", "Standard", "Free Defense Upgrade", 0.01, "Earn 350 medals Gravity event", 0);
        relic("Shadow Puppet", "Epic", "Standard", "Super Critical Mult", 0.05, "Earn 700 medals Dark Strands (II) event", 0);
        relic("Power Glove", "Rare", "Standard", "Damage", 0.02, "Earn 350 medals Retro Arcade (II) event", 1);
        relic("Cursed Candle", "Epic", "Premium", "Super Critical Chance", 0.02, "Premium 1100 medals Dark Strands (II) event", 1);
        relic("Coral Crown", "Rare", "Standard", "Health Regen", 0.02, "Earn 350 medals Deep Blue Sea (II) event", 1);
        relic("Light Speedometer", "Epic", "Standard", "Enemy Attack Level Skip", 0.02, "Earn 700 medals Faster Than Light (II) event", 1);
        relic("Temporal Rift", "Rare", "Standard", "Cash", 0.02, "Earn 350 medals What Time Is It? event", 1);
        relic("Photon Blade", "Epic", "Premium", "Damage", 0.05, "Premium 1100 medals Faster Than Light (II) event", 0);
        relic("Hourglass", "Rare", "Premium", "Coins", 0.02, "Premium 550 medals What Time Is It? event", 0);
        relic("Candy Core", "Epic", "Standard", "Damage", 0.05, "Earn 700 medals Easter (II) event", 0);
        relic("Throne", "Rare", "Guild", "Health", 0.02, "Spend 75 guild tokens Guild Season 1", 0);
        relic("Magic Egg", "Epic", "Premium", "Free Attack Upgrade", 0.02, "Premium 1100 medals Easter (II) event", 0);
        relic("Haunted Mirror", "Rare", "Standard", "Wall Rebuild", 2.0, "Earn 350 medals Dark Strands (II) event", 0);
        relic("Mech Head", "Epic", "Guild", "Bot Range", 2.0, "Spend 150 Tokens in Guild Season 2", 1);
        relic("Whispering Web", "Rare", "Premium", "Free Defense Upgrade", 0.01, "Premium 550 medals Dark Strands (II) event", 0);
        relic("Do While True", "Epic", "Standard", "Orb Speed", 0.05, "Earn 700 medals Pi event", 1);
        relic("Pulsar Core", "Rare", "Standard", "Recovery Amount", 0.02, "Earn 350 medals Faster Than Light (II) event", 0);
        relic("Psychohistorian Brain", "Epic", "Premium", "Super Critical Chance", 0.02, "Premium 1100 medals Pi event", 0);
        relic("Quantum Drive", "Rare", "Premium", "Bot Range", 1.0, "Premium 550 medals Faster Than Light (II) event", 0);
        relic("Alien Egg", "Epic", "Standard", "Enemy Health Level Skip", 0.02, "Earn 700 medals Invaders (II) event", 1);
        relic("Bloom Burst", "Rare", "Standard", "Cash", 0.02, "Earn 350 medals Easter (II) event", 1);
        relic("Monolith", "Epic", "Premium", "Ultimate Damage", 0.05, "Premium 1100 medals Invaders (II) event", 1);
        relic("Mystic Bunny", "Rare", "Premium", "Coins", 0.02, "Premium 550 medals Easter (II) event", 0);
        relic("Honey Society", "Epic", "Standard", "Knockback Force", 0.05, "Earn 700 medals Honey (III) event", 1);
        relic("Fancy Wires", "Rare", "Guild", "Health Regen", 0.02, "Spend 75 guild tokens Guild Season 2", 1);
        relic("The Queen", "Epic", "Premium", "Coins", 0.05, "Premium 1100 medals Honey (III) event", 1);
        relic("Infinite Ruler", "Rare", "Standard", "Free Utility Upgrade", 0.01, "Earn 350 medals Pi event", 1);
        relic("Wind", "Epic", "Standard", "Damage / Meter", 0.05, "Earn 700 medals Koi Pond event", 1);
        relic("Pi Seal", "Rare", "Premium", "Lab Speed", 0.02, "Premium 550 medals Pi event", 0);
        relic("Lilies", "Epic", "Premium", "Recovery Amount", 0.05, "Premium 1100 medals Koi Pond event", 1);
        relic("UFO Beam", "Rare", "Standard", "Knockback Force", 0.02, "Earn 350 medals Invaders (II) event", 1);
        relic("Night Life", "Epic", "Guild", "Attack Speed", 0.02, "Spend 150 Tokens in Guild Season 3", 1);
        relic("Abduction Signal", "Rare", "Premium", "Crit Factor", 0.02, "Premium 550 medals Invaders (II) event", 1);
        relic("Plasma Cell", "Epic", "Standard", "Crit Chance", 0.02, "Earn 700 medals Plasma Returns (III) event", 1);
        relic("Honey Jar", "Rare", "Standard", "Attack Speed", 0.01, "Earn 350 medals Honey (III) event", 1);
        relic("Plasma Chamber", "Epic", "Premium", "Health", 0.05, "Premium 1100 medals Plasma Returns (III) event", 1);
        relic("Heavenly Sweet", "Rare", "Premium", "Health", 0.02, "Premium 550 medals Honey (III) event", 1);
        relic("Retro Camera", "Epic", "Standard", "Health Regen", 0.05, "Earn 700 medals Retrowave (III) event", 1);
        relic("Duck", "Rare", "Standard", "Ultimate Damage", 0.02, "Earn 350 medals Koi Pond event", 1);
        relic("Night City", "Epic", "Premium", "Cash", 0.05, "Premium 1100 medals Retrowave (III) event", 0);
        relic("Grass", "Rare", "Premium", "Free Defense Upgrade", 0.01, "Premium 550 medals Koi Pond event", 1);
        relic("Eternal Quest", "Epic", "Standard", "Health", 0.05, "Earn 700 medals Camping event", 1);
        relic("Let's Mix", "Rare", "Guild", "Coins", 0.02, "Spend 75 guild tokens Guild Season 3", 1);
        relic("Nature's Wrath", "Epic", "Premium", "Orb Speed", 0.05, "Premium 1100 medals Camping event", 1);
        relic("Plasma Globe", "Rare", "Standard", "Bot Range", 1.0, "Earn 350 medals Plasma Returns (III) event", 1);
        relic("Good Catch", "Epic", "Standard", "Thorns", 0.02, "Earn 700 medals Sunset Fishing (II) event", 1);
        relic("Plasma Vortex", "Rare", "Premium", "Damage", 0.02, "Premium 550 medals Plasma Returns (III) event", 1);
        relic("River Of Plenty", "Epic", "Premium", "Coins", 0.05, "Premium 1100 medals Sunset Fishing (II) event", 1);
        relic("Floppy Disk", "Rare", "Standard", "Free Utility Upgrade", 0.01, "Earn 350 medals Retrowave (III) event", 1);
        relic("Brave Heroes", "Epic", "Guild", "Crit Factor", 0.05, "Spend 150 Tokens in Guild Season 4", 1);
        relic("Magic Cube", "Rare", "Premium", "Crit Factor", 0.02, "Premium 550 medals Retrowave (III) event", 0);
        relic("Tower Agent", "Epic", "Standard", "Damage / Meter", 0.05, "Earn 700 medals Into the Matrix (III) event", 1);
        relic("Safe Path", "Rare", "Standard", "Damage", 0.02, "Earn 350 medals Camping event", 1);
        relic("Fake Reality", "Epic", "Premium", "Ultimate Damage", 0.05, "Premium 1100 medals Into the Matrix (III) event", 1);
        relic("Shining Light", "Rare", "Premium", "Crit Chance", 0.01, "Premium 550 medals Camping event", 1);
        relic("Cosmic Freedom", "Epic", "Standard", "Health Regen", 0.05, "Earn 700 medals Cthulhu event", 1);
        relic("Fisherman Set", "Rare", "Standard", "Defense Absolute", 0.02, "Earn 350 medals Sunset Fishing (II) event", 1);
        relic("Omniscience", "Epic", "Premium", "Cash", 0.05, "Premium 1100 medals Cthulhu event", 0);
        relic("Sunset Boat", "Rare", "Premium", "Attack Speed", 0.01, "Premium 550 medals Sunset Fishing (II) event", 1);
        relic("No Signal", "Epic", "Standard", "Crit Chance", 0.02, "Earn 700 medals Tower's Channel (II) event", 1);
        relic("World Domination", "Rare", "Guild", "Health", 0.02, "Spend 75 guild tokens Guild Season 4", 1);
        relic("Antenna", "Epic", "Premium", "Health", 0.05, "Premium 1100 medals Tower's Channel (II) event", 1);
        relic("Model Training", "Rare", "Standard", "Orb Speed", 0.02, "Earn 350 medals Into the Matrix (III) event", 1);
        relic("Glowing Mushrooms", "Epic", "Standard", "Thorns", 0.02, "Earn 700 medals Autumn (III) event", 1);
        relic("Gnosis", "Rare", "Premium", "Free Defense Upgrade", 0.01, "Premium 550 medals Into the Matrix (III) event", 1);
        relic("Warm Clothes", "Epic", "Premium", "Lab Speed", 0.04, "Premium 1100 medals Autumn (III) event", 1);
        relic("Rlyeh", "Rare", "Standard", "Free Attack Upgrade", 0.01, "Earn 350 medals Cthulhu event", 1);
        relic("Glimpse of Despair", "Epic", "Guild", "Crit Factor", 0.05, "Spend 150 Tokens in Guild Season 5", 1);
        relic("Madness Induced", "Rare", "Premium", "Crit Factor", 0.02, "Premium 550 medals Cthulhu event", 0);
        relic("Tech Weapon", "Epic", "Standard", "Recovery Amount", 0.05, "Earn 700 medals Cyberpunk event", 1);
        relic("Breaking News", "Rare", "Standard", "Bot Range", 1.0, "Earn 350 medals Tower's Channel (II) event", 1);
        relic("Cybernetics", "Epic", "Premium", "Crit Chance", 0.02, "Premium 1100 medals Cyberpunk event", 1);
        relic("Globalization", "Rare", "Premium", "Damage", 0.02, "Premium 550 medals Tower's Channel (II) event", 1);
        relic("Spider Poison", "Epic", "Standard", "Ultimate Damage", 0.05, "Earn 700 medals Into the Cobweb (III) event", 1);
        relic("Brunch", "Rare", "Standard", "Knockback Force", 0.02, "Earn 350 medals Autumn (III) event", 1);
        relic("Spider Forest", "Epic", "Premium", "Crit Factor", 0.05, "Premium 1100 medals Into Cobweb (III) event", 0);
        relic("Dry leaves", "Rare", "Premium", "Free Attack Upgrade", 0.01, "Premium 550 medals Autumn (III) event", 1);
        relic("Let's Play", "Epic", "Standard", "Damage", 0.05, "Earn 700 medals Retro Arcade (III) event", 1);
        relic("Blood Monster", "Rare", "Guild", "Defense %", 0.01, "Spend 75 guild tokens Guild Season 5", 1);
        relic("Enemies", "Epic", "Premium", "Coins", 0.05, "Premium 1100 medals Retro Arcade (III) event", 1);
        relic("Vr", "Rare", "Standard", "Thorns", 0.01, "Earn 350 medals Cyberpunk event", 1);
        relic("Crystals Bag", "Epic", "Standard", "Knockback Force", 0.05, "Earn 700 medals Crystal Cave event", 1);
        relic("Holographic Ads", "Rare", "Premium", "Lab Speed", 0.02, "Premium 550 medals Cyberpunk event", 1);
        relic("Full Minecart", "Epic", "Premium", "Bot Range", 2.0, "Premium 1100 medals Crystal Cave event", 1);
        relic("Good Hunting", "Rare", "Standard", "Cash", 0.02, "Earn 350 medals Cobweb (III) event", 1);
        relic("Star Planet", "Epic", "Guild", "Health Regen", 0.05, "Spend 150 Tokens in Guild Season 6", 1);
        relic("Spider Vision", "Rare", "Premium", "Orb Speed", 0.02, "Premium 550 medals Cobweb (III) event", 0);
        relic("Snowflake", "Epic", "Standard", "Damage / Meter", 0.05, "Earn 700 medals Snowstorm (II) event", 1);
        relic("Pinball", "Rare", "Standard", "Defense Absolute", 0.02, "Earn 350 medals Retro Arcade (III) event", 1);
        relic("Christmas Wreath", "Epic", "Premium", "Damage", 0.05, "Premium 1100 medals Snowstorm (II) event", 1);
        relic("To Infinity", "Rare", "Premium", "Health Regen", 0.02, "Premium 550 medals Retro Arcade (III) event", 1);
        relic("Firework Rocket", "Epic", "Standard", "Free Utility Upgrade", 0.02, "Earn 700 medals New Year (III) event", 1);
        relic("Explorer's Helmet", "Rare", "Standard", "Health", 0.02, "Earn 350 medals Crystal Cave event", 1);
        relic("Gift box", "Epic", "Premium", "Lab Speed", 0.04, "Premium 1100 medals New Year (III) event", 1);
        relic("Miner's Tool", "Rare", "Premium", "Defense %", 0.01, "Premium 550 medals Crystal Cave event", 1);
        relic("Amazing Prizes", "Epic", "Standard", "Thorns", 0.02, "Earn 700 medals Amusement Park event", 1);
        relic("Star Path", "Rare", "Guild", "Free Attack Upgrade", 0.02, "Spend 75 guild tokens Guild Season 6", 1);
        relic("Carousel Of Joy", "Epic", "Premium", "Coins", 0.05, "Premium 1100 medals Amusement Park event", 1);
        relic("Snow Globe", "Rare", "Standard", "Recovery Amount", 0.02, "Earn 350 medals Snowstorm (II) event", 1);
        relic("Northern Mountains", "Epic", "Standard", "Defense %", 0.02, "Earn 700 medals Aurora (III) event", 1);
        relic("Winter Gloves", "Rare", "Premium", "Thorns", 0.01, "Premium 550 medals Snowstorm (II) event", 1);
        relic("Cosmic Impact", "Epic", "Premium", "Orb Speed", 0.05, "Premium 1100 medals Aurora (III) event", 0);
        relic("Party Popper", "Rare", "Standard", "Free Attack Upgrade", 0.01, "Earn 350 medals New Year (III) event", 1);
        relic("Quasar", "Epic", "Guild", "Health", 0.05, "Spend 150 Tokens in Guild Season 7", 1);
        relic("Champagne", "Rare", "Premium", "Attack Speed", 0.01, "Premium 550 medals New Year (III) event", 1);
        relic("Crop Circles", "Epic", "Standard", "Knockback Force", 0.05, "Earn 700 medals Aliens (III) event", 1);
        relic("Hapiness Balloons", "Rare", "Standard", "Defense Absolute", 0.02, "Earn 350 medals Amusement Park event", 1);
        relic("Alien Implants", "Epic", "Premium", "Ultimate Damage", 0.05, "Premium 1100 medals Aliens (III) event", 1);
        relic("Delicious Food", "Rare", "Premium", "Cash", 0.02, "Premium 550 medals Amusement Park event", 1);
        relic("Lovely Gift", "Epic", "Standard", "Knockback Force", 0.05, "Earn 700 medals Valentine event", 1);
        relic("Sky's Curtain", "Rare", "Standard", "Free Defense Upgrade", 0.01, "Earn 350 medals Aurora (III) event", 1);
        relic("Pierced Heart", "Epic", "Premium", "Ultimate Damage", 0.05, "Premium 1100 medals Valentine event", 1);
        relic("Solar Flare", "Rare", "Premium", "Crit Chance", 0.01, "Premium 550 medals Aurora (III) event", 0);
        relic("Sailing At Night", "Epic", "Standard", "Health", 0.05, "Earn 700 medals Ocean Night (III) event", 1);
        relic("Elemental Explosion", "Rare", "Guild", "Rend Armor Mult", 0.02, "Spend 75 guild tokens Guild Season 7", 1);
        relic("Moonlight", "Epic", "Premium", "Crit Factor", 0.05, "Premium 1100 medals Ocean Night (III) event", 1);
        relic("Sudden Attack", "Rare", "Standard", "Health Regen", 0.02, "Earn 350 medals Aliens (III) event", 1);
        relic("Forest Temple", "Epic", "Standard", "Thorns", 0.02, "Earn 700 medals Cherry Blossom (IV) event", 1);
        relic("Alien Experiment", "Rare", "Premium", "Bot Range", 1.0, "Premium 550 medals Aliens (III) event", 1);
        relic("Tori", "Epic", "Premium", "Orb Speed", 0.05, "Premium 1100 medals Cherry Blossom (IV) event", 1);
        relic("Bouquet", "Rare", "Standard", "Health", 0.02, "Earn 350 medals Valentine event", 1);
        relic("Collector's Spirit", "Epic", "Guild", "Damage", 0.05, "Spend 150 Tokens in Guild Season 8", 1);
        relic("Love Letter", "Rare", "Premium", "Damage / Meter", 0.02, "Premium 550 medals Valentine event", 1);
        relic("Digital Disaster", "Epic", "Standard", "Free Defense Upgrade", 0.02, "Earn 700 medals Glitch event", 1);
        relic("Lighthouse", "Rare", "Standard", "Recovery Amount", 0.02, "Earn 350 medals Ocean Night (III) event", 1);
        relic("Instability", "Epic", "Premium", "Damage / Meter", 0.05, "Premium 1100 medals Glitch event", 1);
        relic("Night Shark", "Rare", "Premium", "Cash", 0.02, "Premium 550 medals Ocean Night (III) event", 1);
        relic("Clock Tower", "Epic", "Standard", "Cash", 0.05, "Earn 700 medals What Time Is It? event", 1);
        relic("Festival Lanterns", "Rare", "Standard", "Knockback Force", 0.02, "Earn 350 medals Cherry Blossom (IV) event", 1);
        relic("Brain Net", "Epic", "Standard", "Free Utility Upgrade", 0.02, "Earn 700 medals Neuron event", 1);
        relic("Ramen", "Rare", "Premium", "Free Utility Upgrade", 0.01, "Premium 550 medals Cherry Blossom (IV) event", 1);
        relic("Time Travel", "Epic", "Premium", "Crit Chance", 0.02, "Premium 1100 medals What Time Is It? event", 1);
        relic("Perfect Catch", "Rare", "Guild", "Free Utility Upgrade", 0.01, "Spend 75 guild tokens Guild Season 8", 1);
        relic("Body Control", "Epic", "Premium", "Ultimate Damage", 0.05, "Premium 1100 medals Neuron event", 1);
        relic("Broken Security", "Rare", "Standard", "Health Regen", 0.02, "Earn 350 medals Glitch event", 1);
        relic("Natural Fire", "Epic", "Premium", "Health Regen", 0.05, "Premium: Earn 700 medals during the \"Into the Storm event (II)", 1);
        relic("Research Object", "Rare", "Premium", "Damage", 0.02, "Premium 550 medals Glitch event", 1);
        relic("Storm Planet", "Epic", "Premium", "Lab Speed", 0.04, "Premium: Earn 1100 medals during the \"Into the Storm event (II)", 1);
        relic("Dangerous Tricks", "Epic", "Guild", "Attack Speed", 0.02, "Spend 150 Tokens in Guild Season 9", 1);
        relic("Ancient Times", "Rare", "Standard", "Defense Absolute", 0.02, "Earn 350 medals What Time Is It? event", 1);
        relic("Space Distortion", "Rare", "Premium", "Attack Speed", 0.01, "Premium 550 medals What Time Is It? event", 1);
        relic("Nature's Fury", "Rare", "Standard", "Defense %", 0.01, "Earn 350 medals Into the Storm event", 1);
        relic("Big Tornado", "Rare", "Premium", "Damage / Meter", 0.02, "Premium 550 medals Into the Storm event", 1);
        relic("Synapse", "Rare", "Standard", "Knockback Force", 0.02, "Earn 350 medals Neuron event", 1);
        relic("Neural Network", "Rare", "Premium", "Coins", 0.02, "Premium 550 medals Neuron event", 1);
        relic("Magic Cards", "Rare", "Guild", "Free Utility Upgrade", 0.01, "Spend 75 guild tokens Guild Season 9", 0);
        relic("Viral Infection", "Rare", "Standard", "Health", 0.02, "Earn 350 medals Viral Outbreak event", 1);
        relic("Immunization", "Rare", "Premium", "Crit Chance", 0.01, "Premium 550 medals Viral Outbreak event", 0);
        relic("Personal Care", "Epic", "Standard", "Free Defense Upgrade", 0.02, "Earn 700 medals Viral Outbreak event", 1);
        relic("Global Threat", "Epic", "Premium", "Crit Factor", 0.05, "Premium 1100 medals Viral Outbreak event", 0);
    }

    private void relic(String name, String rarity, String type, String bonusStat,
                       double bonusValue, String obtainCondition, int owned) {
        Long id = jdbc.queryForObject(
            "INSERT OR IGNORE INTO relic (name, rarity, type, bonus_stat, bonus_value, obtain_condition) " +
            "VALUES (?,?,?,?,?,?) RETURNING id",
            Long.class, name, rarity, type, bonusStat, bonusValue, obtainCondition);
        if (id != null) {
            jdbc.update("INSERT OR IGNORE INTO relic_player_state (relic_id, owned) VALUES (?,?)", id, owned);
        }
    }
}
